#logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: true

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # PRODUCT-INVENTORY-SERVICE route configuration
        - id: product-inventory-service
          uri: lb://product-inventory-service
          predicates:
            - Method=GET
            - Path=/gateway/products/{id} # outside path
          filters:
            - SetPath=/products/inventory/{id} # mapped to service path

        # ORDER-SERVICE route configuration
        - id: order-service
          uri: lb://order-service
          predicates:
            - Method=POST
            - Path=/gateway/orders/quotation # outside path
          filters:
            - SetPath=/orders/quotation # mapped to service path

        - id: order-service
          uri: lb://order-service
          predicates:
            - Method=POST
            - Path=/gateway/orders/confirm
          filters:
            - SetPath=/orders/confirm
